server:
  port: 7805
security:
  basic:
    enabled: false

feign:
  hystrix:
    enabled: true

eureka:
  instance:
      hostname: localhost
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    healthcheck:
      enable: true

spring:
  application:
    name: micro-server2-hystrix-movie-feign

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000