server:
  port: 7804

eureka:
  instance:
      hostname: localhost
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    healthcheck:
      enable: true

spring:
  application:
    name: micro-server-movie-feign-customize

logging:
  level:
    com.mesen.web.interfacecontroller: DEBUG