server:
  port: 8772

spring:
  application:
    name: ms5-scconfig-eureka

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
